name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          java-version: |
            21
            24
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: ./gradlew shadowJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v7
        with:
          name: keycloak-minecraft
          path: build/libs/keycloak-minecraft.jar
          retention-days: 30
